/**
 * AI Maturity Assessment - Seed Data
 * 37 assessment items across 5 domains
 */

export const TEMPLATE_VERSION = 'v1.0';

export const domains = [
  {
    code: 'data',
    name: 'Dữ liệu',
    nameEn: 'Data',
    description: 'Đánh giá khả năng quản lý, chất lượng và sử dụng dữ liệu cho AI',
    weight: 1.0,
    sortOrder: 1,
  },
  {
    code: 'infra',
    name: 'Hạ tầng',
    nameEn: 'Infrastructure',
    description: 'Đánh giá hạ tầng công nghệ, tính toán và lưu trữ',
    weight: 1.0,
    sortOrder: 2,
  },
  {
    code: 'tech',
    name: 'Công nghệ',
    nameEn: 'Technology',
    description: 'Đánh giá năng lực triển khai và vận hành các giải pháp AI',
    weight: 1.0,
    sortOrder: 3,
  },
  {
    code: 'org',
    name: 'Tổ chức & Đầu tư',
    nameEn: 'Organization & Investment',
    description: 'Đánh giá năng lực tổ chức, nguồn lực và đầu tư cho AI',
    weight: 1.0,
    sortOrder: 4,
  },
  {
    code: 'policy',
    name: 'Quy định & Chính sách',
    nameEn: 'Policy & Governance',
    description: 'Đánh giá khung quản trị, tuân thủ và bảo mật AI',
    weight: 1.0,
    sortOrder: 5,
  },
];

export const items = [
  // ============================================================================
  // DOMAIN 1: DỮ LIỆU (Data) - 9 items
  // ============================================================================
  {
    domainCode: 'data',
    itemCode: '1.1',
    itemName: 'Tính chính xác và độ tin cậy của dữ liệu',
    itemNameEn: 'Data Accuracy and Reliability',
    weight: 1.0,
    sortOrder: 1,
    evidenceRequired: true,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'xlsx', 'png', 'jpg', 'url'],
    level1: 'Dữ liệu không được kiểm tra hoặc xác thực, có nhiều lỗi và không nhất quán. Không có quy trình kiểm soát chất lượng dữ liệu.',
    level2: 'Có một số kiểm tra dữ liệu cơ bản nhưng không thường xuyên. Vẫn còn nhiều lỗi và không nhất quán trong dữ liệu.',
    level3: 'Có quy trình kiểm tra và xác thực dữ liệu được áp dụng định kỳ. Chất lượng dữ liệu ở mức chấp nhận được cho hầu hết các mục đích.',
    level4: 'Dữ liệu được kiểm tra và xác thực tự động thường xuyên. Có các quy trình xử lý lỗi và điều chỉnh dữ liệu rõ ràng.',
    level5: 'Hệ thống kiểm soát chất lượng dữ liệu hoàn toàn tự động với giám sát liên tục. Dữ liệu đạt chuẩn chính xác cao cho các ứng dụng AI quan trọng.',
  },
  {
    domainCode: 'data',
    itemCode: '1.2',
    itemName: 'Khả năng truy cập và tích hợp dữ liệu',
    itemNameEn: 'Data Accessibility and Integration',
    weight: 1.0,
    sortOrder: 2,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'png', 'url'],
    level1: 'Dữ liệu lưu trữ phân tán, khó truy cập. Không có API hoặc công cụ tích hợp dữ liệu giữa các hệ thống.',
    level2: 'Dữ liệu có thể truy cập được nhưng cần can thiệp thủ công. Một số hệ thống có kết nối cơ bản.',
    level3: 'Có data lake hoặc data warehouse trung tâm. API và connector cơ bản đã được triển khai cho các hệ thống chính.',
    level4: 'Dữ liệu từ nhiều nguồn được tích hợp tự động vào nền tảng trung tâm. Có data catalog và metadata management.',
    level5: 'Nền tảng dữ liệu thống nhất với real-time data streaming, API mở và khả năng self-service cho người dùng. Data mesh hoặc data fabric đã triển khai.',
  },
  {
    domainCode: 'data',
    itemCode: '1.3',
    itemName: 'Quản trị và bảo mật dữ liệu',
    itemNameEn: 'Data Governance and Security',
    weight: 1.0,
    sortOrder: 3,
    evidenceRequired: true,
    evidenceRequiredIfLe: 3,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có chính sách quản trị dữ liệu. Bảo mật dữ liệu không được quan tâm hoặc chỉ ở mức cơ bản.',
    level2: 'Có một số quy định về quản trị dữ liệu nhưng chưa được áp dụng rộng rãi. Bảo mật ở mức cơ bản với phân quyền đơn giản.',
    level3: 'Đã có khung quản trị dữ liệu (data governance framework) được phê duyệt. Phân loại dữ liệu theo độ nhạy cảm và áp dụng kiểm soát truy cập.',
    level4: 'Quản trị dữ liệu được tích hợp vào quy trình vận hành. Có data steward và DPO. Bảo mật dữ liệu bao gồm encryption, masking, audit trail.',
    level5: 'Quản trị dữ liệu tự động với AI/ML. Zero-trust security model. Tuân thủ đầy đủ các quy định (GDPR, PDPA, v.v.) với kiểm toán định kỳ.',
  },
  {
    domainCode: 'data',
    itemCode: '1.4',
    itemName: 'Chuẩn hóa và tài liệu hóa dữ liệu',
    itemNameEn: 'Data Standardization and Documentation',
    weight: 1.0,
    sortOrder: 4,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Dữ liệu không có chuẩn hóa. Không có tài liệu hoặc metadata mô tả dữ liệu.',
    level2: 'Một số định dạng dữ liệu được chuẩn hóa ở cấp độ đơn vị. Tài liệu dữ liệu tồn tại nhưng không đầy đủ.',
    level3: 'Có tiêu chuẩn dữ liệu được áp dụng cho các hệ thống chính. Data dictionary và metadata catalog cơ bản đã có.',
    level4: 'Chuẩn hóa dữ liệu được áp dụng rộng rãi trên toàn tổ chức. Data catalog với lineage tracking và business glossary.',
    level5: 'Chuẩn hóa dữ liệu hoàn toàn tự động. Metadata management platform với AI-powered data discovery và auto-documentation.',
  },
  {
    domainCode: 'data',
    itemCode: '1.5',
    itemName: 'Khối lượng và đa dạng dữ liệu',
    itemNameEn: 'Data Volume and Variety',
    weight: 1.0,
    sortOrder: 5,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Dữ liệu hạn chế về khối lượng và loại hình (chủ yếu dữ liệu structured). Không đủ dữ liệu để training AI models.',
    level2: 'Có một lượng dữ liệu reasonable nhưng chủ yếu structured data. Bắt đầu thu thập unstructured data (text, images).',
    level3: 'Dữ liệu đa dạng bao gồm structured, semi-structured và unstructured. Khối lượng dữ liệu đủ cho các use case AI cơ bản.',
    level4: 'Big data platform xử lý đa dạng loại dữ liệu (text, image, video, sensor, logs). Dữ liệu lịch sử phong phú (>3 năm).',
    level5: 'Khối lượng và đa dạng dữ liệu ở quy mô enterprise với real-time streaming. Bao gồm external data sources và synthetic data generation.',
  },
  {
    domainCode: 'data',
    itemCode: '1.6',
    itemName: 'Khả năng làm sạch và chuẩn bị dữ liệu (Data Preparation)',
    itemNameEn: 'Data Cleaning and Preparation Capability',
    weight: 1.0,
    sortOrder: 6,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'png'],
    level1: 'Làm sạch dữ liệu thủ công, không có quy trình chuẩn. Tốn nhiều thời gian và dễ lỗi.',
    level2: 'Có một số scripts hoặc tools cơ bản cho data cleaning nhưng chưa tự động hóa hoàn toàn.',
    level3: 'Quy trình ETL/ELT được thiết lập với các công cụ như Airflow, dbt. Data cleaning được tự động hóa cho các pipeline chính.',
    level4: 'Data preparation platform với GUI cho citizen data scientists. Auto-detection của outliers, missing values và data quality issues.',
    level5: 'AI-powered data preparation với tự động feature engineering, anomaly detection và data augmentation. Self-healing data pipelines.',
  },
  {
    domainCode: 'data',
    itemCode: '1.7',
    itemName: 'Dữ liệu thời gian thực (Real-time Data)',
    itemNameEn: 'Real-time Data Capability',
    weight: 1.0,
    sortOrder: 7,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Chỉ có batch data xử lý định kỳ (hàng ngày/tuần). Không có khả năng streaming.',
    level2: 'Bắt đầu có một số use case near-real-time (micro-batching) nhưng không phổ biến.',
    level3: 'Có streaming data platform cơ bản (Kafka, Kinesis) cho một số use case quan trọng.',
    level4: 'Real-time data streaming được triển khai rộng rãi. Stream processing với Flink/Spark Streaming cho analytics và ML.',
    level5: 'Event-driven architecture với real-time AI inference. Complex event processing (CEP) và real-time model serving ở quy mô lớn.',
  },
  {
    domainCode: 'data',
    itemCode: '1.8',
    itemName: 'Khả năng gán nhãn và annotation dữ liệu',
    itemNameEn: 'Data Labeling and Annotation Capability',
    weight: 1.0,
    sortOrder: 8,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'png', 'url'],
    level1: 'Không có quy trình gán nhãn dữ liệu. Dữ liệu không được label cho supervised learning.',
    level2: 'Gán nhãn thủ công bởi nhóm nhỏ. Không có công cụ hỗ trợ và quality control.',
    level3: 'Có công cụ annotation (Labelbox, CVAT) và quy trình gán nhãn có cấu trúc. Quality assurance cơ bản.',
    level4: 'Annotation platform với workflow management, inter-annotator agreement tracking và active learning để tối ưu labeling.',
    level5: 'AI-assisted annotation với semi-supervised và self-supervised learning. Synthetic data generation để giảm nhu cầu manual labeling.',
  },
  {
    domainCode: 'data',
    itemCode: '1.9',
    itemName: 'Quản lý vòng đời dữ liệu (Data Lifecycle Management)',
    itemNameEn: 'Data Lifecycle Management',
    weight: 1.0,
    sortOrder: 9,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có chính sách quản lý vòng đời dữ liệu. Dữ liệu được lưu trữ vô thời hạn mà không phân loại.',
    level2: 'Có một số quy định về retention và deletion nhưng chưa được thực thi nhất quán.',
    level3: 'Data retention policies được định nghĩa và áp dụng. Dữ liệu được archiving định kỳ.',
    level4: 'Automated data lifecycle management với tiered storage (hot/warm/cold). Data lineage và versioning được theo dõi.',
    level5: 'Intelligent data lifecycle với AI-driven archival policies. Automated compliance với GDPR right-to-be-forgotten và data minimization.',
  },

  // ============================================================================
  // DOMAIN 2: HẠ TẦNG (Infrastructure) - 3 items
  // ============================================================================
  {
    domainCode: 'infra',
    itemCode: '2.1',
    itemName: 'Năng lực điện toán (Computing Power)',
    itemNameEn: 'Computing Power',
    weight: 1.0,
    sortOrder: 1,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'xlsx', 'png'],
    level1: 'Hạ tầng điện toán hạn chế, chủ yếu CPU thông thường. Không đủ resource cho training AI models.',
    level2: 'Có một số servers mạnh hơn hoặc VM với nhiều CPU cores. Bắt đầu có GPUs nhưng số lượng hạn chế.',
    level3: 'Có GPU cluster hoặc access tới cloud GPU instances (AWS, GCP, Azure). Đủ để train các models cỡ vừa.',
    level4: 'Dedicated AI infrastructure với multi-GPU nodes, high-bandwidth networking. Có khả năng distributed training.',
    level5: 'Enterprise-scale AI infrastructure với TPUs/GPUs clusters, HPC, và khả năng train large language models (LLMs). Auto-scaling và resource optimization.',
  },
  {
    domainCode: 'infra',
    itemCode: '2.2',
    itemName: 'Lưu trữ và hệ thống dữ liệu (Storage Systems)',
    itemNameEn: 'Storage Systems',
    weight: 1.0,
    sortOrder: 2,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'png'],
    level1: 'Lưu trữ cơ bản với databases quan hệ truyền thống. Storage dung lượng nhỏ, không scale được.',
    level2: 'Có NAS/SAN hoặc cloud storage (S3, Blob). Bắt đầu có data warehouse nhưng chưa tối ưu cho analytics.',
    level3: 'Data lake hoặc modern data warehouse (Snowflake, BigQuery, Redshift). Có khả năng lưu trữ và truy vấn big data.',
    level4: 'Multi-tier storage với object storage, distributed file systems (HDFS, MinIO) và high-performance databases. Optimized cho ML workloads.',
    level5: 'Lakehouse architecture với Delta Lake/Iceberg. Unified storage layer với ACID transactions, time travel và schema evolution cho AI/ML.',
  },
  {
    domainCode: 'infra',
    itemCode: '2.3',
    itemName: 'Cloud và khả năng mở rộng (Cloud & Scalability)',
    itemNameEn: 'Cloud and Scalability',
    weight: 1.0,
    sortOrder: 3,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Hoàn toàn on-premise với infrastructure cố định. Không có khả năng scale nhanh.',
    level2: 'Hybrid cloud với một số workloads trên cloud. Manual scaling với lead time dài.',
    level3: 'Cloud-first strategy với auto-scaling cho compute và storage. Sử dụng managed services (RDS, EMR, SageMaker).',
    level4: 'Multi-cloud hoặc cloud-native architecture với containers (Kubernetes). Elastic scaling và cost optimization.',
    level5: 'Serverless và event-driven architecture cho AI workloads. FinOps practices với automated resource optimization và spot instance strategies.',
  },

  // ============================================================================
  // DOMAIN 3: CÔNG NGHỆ (Technology) - 6 items
  // ============================================================================
  {
    domainCode: 'tech',
    itemCode: '3.1',
    itemName: 'Công cụ và framework AI/ML',
    itemNameEn: 'AI/ML Tools and Frameworks',
    weight: 1.0,
    sortOrder: 1,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'png', 'url'],
    level1: 'Không có công cụ AI/ML. Chỉ sử dụng Excel hoặc BI tools cơ bản cho analytics.',
    level2: 'Bắt đầu thử nghiệm với scikit-learn, pandas cho các mô hình đơn giản (regression, classification).',
    level3: 'Sử dụng các frameworks phổ biến như TensorFlow, PyTorch cho deep learning. Có Jupyter notebooks và experiment tracking.',
    level4: 'MLOps platform với MLflow, Kubeflow hoặc SageMaker. Model registry, versioning và automated retraining.',
    level5: 'Enterprise AI platform với AutoML, feature store, model marketplace và A/B testing framework. LLMOps cho generative AI.',
  },
  {
    domainCode: 'tech',
    itemCode: '3.2',
    itemName: 'Năng lực phát triển và triển khai models',
    itemNameEn: 'Model Development and Deployment',
    weight: 1.0,
    sortOrder: 2,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'png'],
    level1: 'Models được phát triển ad-hoc, không có quy trình chuẩn. Deployment thủ công và không reliable.',
    level2: 'Có một số quy trình phát triển nhưng chủ yếu manual. Models được deploy ở môi trường dev/test.',
    level3: 'CI/CD pipeline cho ML models. Containerization với Docker. Models được deploy lên staging trước production.',
    level4: 'Automated ML pipelines với training, validation và deployment. Model serving với REST APIs hoặc gRPC. Monitoring và alerting.',
    level5: 'GitOps cho ML với automated retraining triggers, canary deployments, shadow mode testing và automated rollback. Real-time serving với <100ms latency.',
  },
  {
    domainCode: 'tech',
    itemCode: '3.3',
    itemName: 'Giám sát và bảo trì models (Model Monitoring)',
    itemNameEn: 'Model Monitoring and Maintenance',
    weight: 1.0,
    sortOrder: 3,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'png', 'url'],
    level1: 'Models được deploy nhưng không có monitoring. Không biết khi nào model performance giảm.',
    level2: 'Basic monitoring với logging. Manual checks định kỳ cho model performance.',
    level3: 'Automated monitoring cho model metrics (accuracy, precision, recall). Alerting khi metrics vượt ngưỡng.',
    level4: 'Comprehensive monitoring bao gồm data drift, concept drift, và fairness metrics. Automated retraining workflows.',
    level5: 'AI-powered model observability với explainability (SHAP, LIME), bias detection, và continuous learning. Self-healing models với automated interventions.',
  },
  {
    domainCode: 'tech',
    itemCode: '3.4',
    itemName: 'Tích hợp AI vào ứng dụng và quy trình nghiệp vụ',
    itemNameEn: 'AI Integration into Applications and Business Processes',
    weight: 1.0,
    sortOrder: 4,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'AI models chạy standalone, không tích hợp vào ứng dụng. Chỉ có POCs hoặc demos.',
    level2: 'Một vài models được tích hợp vào ứng dụng nhưng loosely coupled. Integration thủ công.',
    level3: 'AI models được expose qua APIs và tích hợp vào business applications. Có error handling và fallback logic.',
    level4: 'AI-first applications với models là core component. Real-time inference trong user workflows. A/B testing để optimize model impact.',
    level5: 'AI deeply embedded trong toàn bộ value chain. Intelligent automation với RPA + AI. Continuous optimization based on business outcomes.',
  },
  {
    domainCode: 'tech',
    itemCode: '3.5',
    itemName: 'Sử dụng AI/GenAI có sẵn (Pre-trained Models & APIs)',
    itemNameEn: 'Use of Pre-trained Models and AI APIs',
    weight: 1.0,
    sortOrder: 5,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Không sử dụng pre-trained models hoặc AI APIs. Build everything from scratch.',
    level2: 'Bắt đầu sử dụng open-source pre-trained models (BERT, ResNet) nhưng chưa fine-tune.',
    level3: 'Sử dụng cloud AI services (AWS Rekognition, Google Vision, Azure Cognitive Services) cho các tác vụ cơ bản.',
    level4: 'Fine-tuning pre-trained models cho domain-specific use cases. Sử dụng LLM APIs (OpenAI, Anthropic) với prompt engineering.',
    level5: 'RAG (Retrieval-Augmented Generation) pipelines, vector databases và enterprise LLM platform. Custom model hosting với foundation model fine-tuning.',
  },
  {
    domainCode: 'tech',
    itemCode: '3.6',
    itemName: 'Bảo mật AI và Responsible AI',
    itemNameEn: 'AI Security and Responsible AI',
    weight: 1.0,
    sortOrder: 6,
    evidenceRequired: true,
    evidenceRequiredIfLe: 3,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có biện pháp bảo mật cụ thể cho AI. Không quan tâm tới bias, fairness hay explainability.',
    level2: 'Awareness về AI security và ethics nhưng chưa có actions cụ thể. Ad-hoc testing cho bias.',
    level3: 'Có guidelines cho Responsible AI. Testing cho bias, fairness và adversarial robustness trong development phase.',
    level4: 'Responsible AI framework được tích hợp vào ML pipelines. Red-teaming và security testing. Bias mitigation techniques.',
    level5: 'AI governance board, model cards, audit trails và compliance automation. Differential privacy, federated learning và encrypted ML cho sensitive data.',
  },

  // ============================================================================
  // DOMAIN 4: TỔ CHỨC & ĐẦU TƯ (Organization & Investment) - 14 items
  // ============================================================================
  {
    domainCode: 'org',
    itemCode: '4.1',
    itemName: 'Chiến lược AI của tổ chức',
    itemNameEn: 'Organizational AI Strategy',
    weight: 1.0,
    sortOrder: 1,
    evidenceRequired: true,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có chiến lược AI. AI chỉ là buzzword hoặc POCs rời rạc.',
    level2: 'Bắt đầu nhận thức về tầm quan trọng của AI nhưng chưa có chiến lược rõ ràng. Top-down hoặc bottom-up initiatives không liên kết.',
    level3: 'Có chiến lược AI được ban lãnh đạo phê duyệt. Roadmap 1-2 năm với các use cases ưu tiên và KPIs.',
    level4: 'AI strategy được tích hợp vào corporate strategy. Cross-functional governance và executive sponsorship. Regular review và pivot based on outcomes.',
    level5: 'AI-first transformation với CEO/Board oversight. AI embedded trong mọi business unit. Continuous innovation với venture/M&A activities.',
  },
  {
    domainCode: 'org',
    itemCode: '4.2',
    itemName: 'Nguồn lực nhân sự AI/ML',
    itemNameEn: 'AI/ML Human Resources',
    weight: 1.0,
    sortOrder: 2,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không có chuyên gia AI/ML trong tổ chức. Phụ thuộc hoàn toàn vào vendor.',
    level2: 'Có 1-2 data scientists hoặc ML engineers nhưng thiếu kinh nghiệm và resources.',
    level3: 'Team AI/ML từ 5-10 người với skills đa dạng (data engineering, ML engineering, research). Bắt đầu có career path.',
    level4: 'Center of Excellence (CoE) cho AI với 20+ members. Specialized roles: MLOps, ML platform, research scientists, solution architects.',
    level5: 'AI talent distributed across organization với centralized platform team. Continuous upskilling, internal mobility và competitive compensation to retain top talent.',
  },
  {
    domainCode: 'org',
    itemCode: '4.3',
    itemName: 'Đào tạo và phát triển năng lực AI',
    itemNameEn: 'AI Training and Capability Development',
    weight: 1.0,
    sortOrder: 3,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Không có chương trình đào tạo AI. Nhân viên tự học hoặc không quan tâm.',
    level2: 'Ad-hoc training sessions hoặc online courses (Coursera, Udemy) cho một số cá nhân.',
    level3: 'Structured training program cho AI literacy (executives), citizen data scientists và technical roles. Annual training budget.',
    level4: 'Comprehensive AI academy với learning paths, hands-on labs, certifications và internal knowledge sharing. Partnerships với universities.',
    level5: 'Continuous learning culture với AI guilds, hackathons, research collaborations và rotation programs. Contribution to open-source và conferences.',
  },
  {
    domainCode: 'org',
    itemCode: '4.4',
    itemName: 'Văn hóa đổi mới và thử nghiệm (Innovation Culture)',
    itemNameEn: 'Innovation and Experimentation Culture',
    weight: 1.0,
    sortOrder: 4,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Văn hóa risk-averse, không khuyến khích thử nghiệm. Failures bị phạt.',
    level2: 'Bắt đầu có một số innovation initiatives nhưng chưa có hỗ trợ đầy đủ từ leadership.',
    level3: 'Innovation labs hoặc sandbox environments. Fail-fast mindset được khuyến khích. Có budget cho experiments.',
    level4: 'Systematic innovation framework (e.g., Stage-Gate). Internal startup program, innovation KPIs và rewards/recognition.',
    level5: 'Innovation is core value. Continuous experimentation với A/B testing, MVPs, và lean startup methodology. Open innovation với ecosystem partners.',
  },
  {
    domainCode: 'org',
    itemCode: '4.5',
    itemName: 'Mô hình tổ chức và cấu trúc team AI',
    itemNameEn: 'Organizational Model and AI Team Structure',
    weight: 1.0,
    sortOrder: 5,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'png'],
    level1: 'Không có team hoặc role chính thức cho AI. AI projects là side projects của IT hoặc analytics team.',
    level2: 'Một vài individuals hoặc small team nhưng không có clear reporting line và mandate.',
    level3: 'Dedicated AI team hoặc CoE báo cáo cho CIO/CDO/CTO. Clear roles & responsibilities.',
    level4: 'Hybrid model: central platform team + embedded AI engineers trong business units. Product-oriented teams.',
    level5: 'AI-native organization với distributed AI capabilities. Chief AI Officer (CAIO) at C-suite. Cross-functional squads với full autonomy.',
  },
  {
    domainCode: 'org',
    itemCode: '4.6',
    itemName: 'Ngân sách và đầu tư cho AI',
    itemNameEn: 'Budget and Investment for AI',
    weight: 1.0,
    sortOrder: 6,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không có budget riêng cho AI. Funding ad-hoc và hạn chế.',
    level2: 'Budget nhỏ (<0.5% revenue/IT budget) cho POCs và pilots.',
    level3: 'Dedicated AI budget (0.5-2% revenue) với annual planning. Business case và ROI tracking.',
    level4: 'Significant investment (2-5% revenue) với multi-year commitment. Portfolio management approach.',
    level5: 'Strategic investment (>5% revenue) với venture arm, M&A và partnerships. AI as competitive differentiator.',
  },
  {
    domainCode: 'org',
    itemCode: '4.7',
    itemName: 'Quan hệ đối tác và hệ sinh thái (Partnerships & Ecosystem)',
    itemNameEn: 'Partnerships and Ecosystem',
    weight: 1.0,
    sortOrder: 7,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Làm việc isolated, không có partnerships. Build everything in-house hoặc rely on single vendor.',
    level2: 'Một vài vendor relationships nhưng transactional. Không có strategic partnerships.',
    level3: 'Partnerships với cloud providers, SI partners và technology vendors. Participation trong industry forums.',
    level4: 'Strategic alliances với tech giants, startups và academia. Co-innovation programs và joint IP development.',
    level5: 'Ecosystem orchestrator với platform approach. Open APIs, developer community và marketplace. Active M&A và venture investments.',
  },
  {
    domainCode: 'org',
    itemCode: '4.8',
    itemName: 'Quản lý dự án và portfolio AI',
    itemNameEn: 'AI Project and Portfolio Management',
    weight: 1.0,
    sortOrder: 8,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không có quản lý dự án chính thức. Projects ad-hoc và thường fail hoặc không finish.',
    level2: 'Basic project management nhưng không có prioritization framework. Projects chạy độc lập.',
    level3: 'PMO cho AI projects với Agile/Scrum methodology. Prioritization based on business value và feasibility.',
    level4: 'Portfolio management với stage-gate process. Balanced portfolio (quick wins, strategic bets, innovation). Regular portfolio reviews.',
    level5: 'Data-driven portfolio optimization với outcome tracking, reallocation và kill/pivot decisions. AI PM tools và predictive analytics.',
  },
  {
    domainCode: 'org',
    itemCode: '4.9',
    itemName: 'Đo lường ROI và impact của AI',
    itemNameEn: 'Measuring ROI and AI Impact',
    weight: 1.0,
    sortOrder: 9,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không đo lường ROI. Không biết AI projects có tạo value hay không.',
    level2: 'Một số metrics ad-hoc nhưng không consistent và không liên kết với business outcomes.',
    level3: 'KPIs defined cho mỗi project. Tracking both technical metrics (accuracy, latency) và business metrics (revenue, cost savings).',
    level4: 'Comprehensive measurement framework với leading/lagging indicators. Attribution modeling để isolate AI impact. Regular reporting tới leadership.',
    level5: 'Real-time dashboards với AI value realization tracking. Causal inference methods để quantify incremental impact. Continuous optimization loop.',
  },
  {
    domainCode: 'org',
    itemCode: '4.10',
    itemName: 'Change management và adoption',
    itemNameEn: 'Change Management and Adoption',
    weight: 1.0,
    sortOrder: 10,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có change management. Users resist AI tools hoặc không biết cách sử dụng.',
    level2: 'Awareness về cần change management nhưng chưa có structured approach. Low adoption rates.',
    level3: 'Change management plan cho mỗi AI initiative. Communication, training và support. User champions và early adopters.',
    level4: 'OCM (Organizational Change Management) team với ADKAR hoặc Kotter methodology. Continuous feedback loops và iteration.',
    level5: 'Change-ready culture với bottom-up innovation. Self-service AI tools với great UX. High adoption rates (>80%) và positive sentiment.',
  },
  {
    domainCode: 'org',
    itemCode: '4.11',
    itemName: 'Collaboration giữa business và IT/AI teams',
    itemNameEn: 'Business and IT/AI Team Collaboration',
    weight: 1.0,
    sortOrder: 11,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Silos giữa business và IT. Không có collaboration, leading to solutions không fit business needs.',
    level2: 'Occasional collaboration nhưng communication gaps. Requirements unclear và thường thay đổi.',
    level3: 'Regular collaboration với product owners từ business side. Co-located teams hoặc embedded AI resources.',
    level4: 'Cross-functional squads với business, data, ML và engineering. Shared OKRs và joint accountability.',
    level5: 'Business-led AI với citizen data scientists. Technical teams enable self-service. Continuous collaboration với design thinking workshops.',
  },
  {
    domainCode: 'org',
    itemCode: '4.12',
    itemName: 'Scalability của operating model',
    itemNameEn: 'Operating Model Scalability',
    weight: 1.0,
    sortOrder: 12,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Operating model không scale. Bottlenecks ở infra, data access, approvals.',
    level2: 'Một số processes nhưng chưa optimize. Manual steps và dependencies.',
    level3: 'Repeatable processes với documentation. Some automation. Có thể scale to 10-20 models.',
    level4: 'Industrialized ML factory. Self-service platforms. Scale to 100+ models.',
    level5: 'Fully automated, AI-native operating model. Scale to 1000+ models. Minimal human intervention.',
  },
  {
    domainCode: 'org',
    itemCode: '4.13',
    itemName: 'Use case ideation và prioritization',
    itemNameEn: 'Use Case Ideation and Prioritization',
    weight: 1.0,
    sortOrder: 13,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không có structured process. Use cases random hoặc HiPPO (Highest Paid Person Opinion).',
    level2: 'Brainstorming sessions nhưng không có framework. Prioritization subjective.',
    level3: 'Use case funnel với scoring (business value, feasibility, data availability). Regularly refreshed backlog.',
    level4: 'Systematic ideation workshops với design thinking. Data-driven prioritization (ICE, RICE, WSJF). Alignment với strategy.',
    level5: 'AI-powered use case discovery. Market scanning và competitive intelligence. Continuous feed of opportunities from frontline.',
  },
  {
    domainCode: 'org',
    itemCode: '4.14',
    itemName: 'Knowledge management và tái sử dụng (Reusability)',
    itemNameEn: 'Knowledge Management and Reusability',
    weight: 1.0,
    sortOrder: 14,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx', 'url'],
    level1: 'Không có knowledge sharing. Mỗi team reinvent the wheel. Code và models không được reuse.',
    level2: 'Ad-hoc documentation. Một số code repos nhưng không organized.',
    level3: 'Internal wiki/confluence. Code repositories với basic documentation. Model registry.',
    level4: 'Knowledge hub với best practices, design patterns, reusable components. Model zoo và feature store. Regular lunch-and-learns.',
    level5: 'AI-powered knowledge platform với semantic search. Auto-documentation. Inner-source culture với high reuse rates (>50%).',
  },

  // ============================================================================
  // DOMAIN 5: QUY ĐỊNH & CHÍNH SÁCH (Policy & Governance) - 5 items
  // ============================================================================
  {
    domainCode: 'policy',
    itemCode: '5.1',
    itemName: 'Chính sách và quy định về AI',
    itemNameEn: 'AI Policies and Regulations',
    weight: 1.0,
    sortOrder: 1,
    evidenceRequired: true,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có chính sách hoặc guidelines về AI. Sử dụng AI ad-hoc mà không có oversight.',
    level2: 'Awareness về cần policies nhưng chưa có formal documentation. Một số informal rules.',
    level3: 'AI policy framework được phê duyệt, bao gồm acceptable use, data privacy, security, ethics. Communicated tới organization.',
    level4: 'Comprehensive AI governance framework với clear roles (AI ethics board, DPO, CISO). Regular audits và compliance checks.',
    level5: 'Living policy framework với continuous updates based on evolving regulations (EU AI Act, GDPR, PDPA). Automated policy enforcement và compliance monitoring.',
  },
  {
    domainCode: 'policy',
    itemCode: '5.2',
    itemName: 'Tuân thủ quy định pháp lý (Legal Compliance)',
    itemNameEn: 'Legal and Regulatory Compliance',
    weight: 1.0,
    sortOrder: 2,
    evidenceRequired: true,
    evidenceRequiredIfLe: 3,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không quan tâm tới legal compliance cho AI. Potential legal risks không được đánh giá.',
    level2: 'Basic awareness về GDPR, PDPA nhưng chưa có actions cụ thể. Reactive approach.',
    level3: 'Compliance program cho data protection và AI regulations. DPIA (Data Protection Impact Assessment) cho high-risk AI systems.',
    level4: 'Proactive compliance với legal team involvement trong AI projects. Regular training, audits và certifications (ISO 27001, SOC 2).',
    level5: 'Compliance-by-design với automated checks. Privacy-preserving AI (differential privacy, federated learning). Full traceability và audit trails.',
  },
  {
    domainCode: 'policy',
    itemCode: '5.3',
    itemName: 'Đạo đức AI và Responsible AI practices',
    itemNameEn: 'AI Ethics and Responsible AI Practices',
    weight: 1.0,
    sortOrder: 3,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không có consideration về AI ethics. Fairness, bias, explainability không được addressed.',
    level2: 'Awareness về ethical issues nhưng chưa có framework. Ad-hoc discussions.',
    level3: 'AI ethics principles defined (fairness, transparency, accountability). Ethical review process cho high-impact use cases.',
    level4: 'Responsible AI framework embedded trong ML lifecycle. Tools cho bias detection, fairness metrics, explainability (SHAP, LIME). Ethics board với diverse perspectives.',
    level5: 'Culture of responsible AI với continuous monitoring. Public reporting (AI transparency reports). Third-party audits và certifications.',
  },
  {
    domainCode: 'policy',
    itemCode: '5.4',
    itemName: 'Quản lý rủi ro AI (AI Risk Management)',
    itemNameEn: 'AI Risk Management',
    weight: 1.0,
    sortOrder: 4,
    evidenceRequired: false,
    evidenceRequiredIfLe: 2,
    allowedFileTypes: ['pdf', 'docx', 'xlsx'],
    level1: 'Không có risk management cho AI. Risks (model failures, adversarial attacks, reputational damage) không được identified.',
    level2: 'Basic risk register nhưng không comprehensive. No mitigation plans.',
    level3: 'AI risk assessment framework (NIST AI RMF). Risk register với likelihood và impact. Mitigation và contingency plans.',
    level4: 'Integrated AI risk management trong enterprise risk management (ERM). Quantitative risk modeling. Regular stress testing.',
    level5: 'Continuous risk monitoring với AI risk dashboards. Scenario planning và war gaming. Cyber insurance covering AI risks.',
  },
  {
    domainCode: 'policy',
    itemCode: '5.5',
    itemName: 'Intellectual Property và ownership',
    itemNameEn: 'Intellectual Property and Ownership',
    weight: 1.0,
    sortOrder: 5,
    evidenceRequired: false,
    evidenceRequiredIfLe: null,
    allowedFileTypes: ['pdf', 'docx'],
    level1: 'Không clear về IP ownership cho AI-generated outputs. Potential legal disputes.',
    level2: 'Basic understanding nhưng chưa có policies. Ad-hoc decisions.',
    level3: 'IP policy covering AI models, training data, và AI-generated content. Clear ownership (organization vs. individuals vs. partners).',
    level4: 'IP management system với patents, trade secrets protection. Licensing agreements cho data và models. Open-source strategy.',
    level5: 'Strategic IP portfolio management. Active patent filing. IP due diligence trong M&A. Monetization strategies (licensing, API access).',
  },
];
